packages:
  - apps/*
  - packages/*

catalog:
  "@tailwindcss/postcss": ^4.1.17
  "@types/node": ^24.10.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3

onlyBuiltDependencies:
  - esbuild
  - lefthook
